from provider.diary_provider import DiaryProvider
from provider.google_photos_provider import GooglePhotosProvider
from provider.immich_provider import ImmichProvider
from provider.instagram_provider import InstagramProvider
from provider.whatsapp_provider import WhatsAppProvider
from provider.imessage_provider import IMessageProvider

# This file has all the customizations for setups

USER = "Ritik"

AVAILABLE_PROVIDERS = [
    WhatsAppProvider,
    InstagramProvider,
    DiaryProvider,
    ImmichProvider,
    GooglePhotosProvider,
    IMessageProvider,
]

# These are the words that are removed from the most common words list
# Should be in lowercase
COMMON_WORDS_FOR_USER_STATS = {
    'i',
    'added',
    'media',
    'file',
    'to',
    'is',
    'and',
    'in',
    'this',
    'for',
    'can',
    'was',
    'but',
    'not',
    'am',
    'it',
    'we',
    'my',
    'us',
    'the',
    'so',
    'you',
    'with',
    'are',
    'he',
    'have',
    'will',
    'do',
    'of',
    'if',
    'that',
    'on',
    'or',
    'from',
    'they',
    'at',
    'as',
    'liked',
    'message',
    'reacted',
    'your',
    'be',
    'bhi',
    'hai',
    'what',
    'yes',
    'nhi',
    'rha',
    'no',
    'ok',
    'get',
    'viral',
    'explore',
    'explorepage',
    'reels',
    'trendingreels',
    'its',
    'who',
    'relatable',
    'funny',
    'trending',
    'all',
    'out',
    'edited',
    'some',
    'follow',
    'memes',
    'viralreels',
    'reelsinstagram',
    'fyp',
    'instagood',
    'foryou',
    'has',
    'about',
    'meme',
    'memesdaily',
    'foryoupage',
    'reelitfeelit',
    'tag',

    # Bit more of may be personal words
    'me',
    'kya',
    'ho',
    'hu',
    'kya',
    'see',
    'kr',
    'ka',
    'ki',
    'good',
    'want',
    'tha',
    'by',
    'one',
    'more',
    'aur',
}
